#
# Module manifest for module 'AvmUpdater'
#
# Generated by: AvmUpdater
#
# Generated on: 29/06/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AvmUpdater.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'fe666ab7-2134-4fb1-8d50-ce40c60f7327'

# Author of this module
Author = 'GetToThe-Cloud'

# Company or vendor of this module
CompanyName = 'GetToThe-Cloud'

# Copyright statement for this module
Copyright = '(c) 2026 GetToThe-Cloud. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Scans Bicep and Terraform files for Azure Verified Module (AVM) references, looks up the latest stable versions, performs risk analysis, generates an approval report, and safely applies updates with per-file rollback on validation failure.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-AvmModuleReference', 'Get-AvmLatestVersion', 'Get-AvmUpdatePlan', 
               'Get-AvmUpdateRisk', 'New-AvmUpdateReport', 'Approve-AvmUpdate', 
               'Update-AvmModuleVersion', 'Invoke-AvmUpdate'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('AVM', 'Bicep', 'Terraform', 'Azure', 'AzureVerifiedModules', 'IaC', 'DevOps', 'Update', 'LandingZone')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/GetToThe-Cloud/avm-updater/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/GetToThe-Cloud/avm-updater'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release. Supports Bicep (MCR) and Terraform Registry AVM modules. Risk tiers: HIGH / MEDIUM / LOW / UNKNOWN. Approval modes: local interactive, GitHub PR, Azure DevOps PR.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

